mod agent;
mod memory;
mod native;
mod settings;

use agent::{AgentContext, AgentPlan, RiskLevel, ToolCall, ToolRegistry, ToolResult};
use serde::{Deserialize, Serialize};
use std::{collections::BTreeMap, fs, path::PathBuf, process::Command};
use tauri::State;
use tokio::sync::Mutex;

#[derive(Default)] pub struct AppState { pub history: Mutex<Vec<(String,String)>> }
#[derive(Serialize, Clone)] pub struct Activity { pub id:String, pub label:String, pub detail:Option<String>, pub status:String, pub at:String }
#[derive(Serialize)] pub struct AskResult { pub reply:String, pub activities:Vec<Activity> }
#[derive(Deserialize)] struct OllamaResponse { response:String }
#[derive(Deserialize)] #[serde(tag="kind", rename_all="snake_case")] enum ModelDecision { Final { response:String }, ToolCall { tool:String, arguments:serde_json::Value } }

fn activity(label:&str, detail:Option<String>, status:&str) -> Activity { Activity{id:format!("{}-{}",chrono::Utc::now().timestamp_nanos_opt().unwrap_or_default(),std::process::id()),label:label.into(),detail,status:status.into(),at:chrono::Local::now().format("%H:%M:%S").to_string()} }
fn memory_path()->PathBuf { dirs::data_local_dir().unwrap_or_else(||PathBuf::from(".")).join("jarvis").join("memory.json") }
fn risk(command:&str)->&'static str { let c=command.to_lowercase(); if ["rm -rf","sudo","diskutil","shutdown","reboot","git reset --hard","git push --force","kill "].iter().any(|x|c.contains(x)){"CRITICAL"} else if ["rm ","delete","drop database","chmod","mv "].iter().any(|x|c.contains(x)){"HIGH"} else if ["npm install","pip install","cargo build","git "].iter().any(|x|c.contains(x)){"MEDIUM"} else {"LOW"} }
fn run_command(command:String,confirmed:bool)->Result<String,String>{let level=risk(&command);if level!="LOW"&&!confirmed{return Err(format!("Confirmation required for {} risk command.",level))}let out=Command::new("sh").args(["-lc",&command]).output().map_err(|e|e.to_string())?;Ok(serde_json::json!({"success":out.status.success(),"risk":level,"stdout":String::from_utf8_lossy(&out.stdout),"stderr":String::from_utf8_lossy(&out.stderr)}).to_string())}
fn open_app_inner(name:String)->Result<String,String>{if !cfg!(target_os="macos"){return Err("Native application control is available in the macOS build; this environment is not macOS.".into())}let status=Command::new("open").args(["-a",&name]).status().map_err(|e|e.to_string())?;if status.success(){Ok(format!("{} launched successfully.",name))}else{Err(format!("macOS rejected the request to open {}.",name))}}
fn tool_result(call:&ToolCall, registry:&ToolRegistry)->ToolResult { let definition=match registry.validate(call){Ok(v)=>v,Err(e)=>return ToolResult{success:false,tool:call.name.clone(),output:serde_json::json!({"error":e}),verified:false}}; if definition.requires_confirmation && !call.arguments.get("confirmed").and_then(|v|v.as_bool()).unwrap_or(false){return ToolResult{success:false,tool:call.name.clone(),output:serde_json::json!({"error":"User confirmation is required before this tool can execute","confirmation_required":true}),verified:false}} let result=match call.name.as_str(){"application.open"=>call.arguments.get("name").and_then(|v|v.as_str()).ok_or("Missing application name").and_then(|n|open_app_inner(n.to_string())),"terminal.run"=>call.arguments.get("command").and_then(|v|v.as_str()).ok_or("Missing command").and_then(|c|run_command(c.to_string(),call.arguments.get("confirmed").and_then(|v|v.as_bool()).unwrap_or(false))),"screen.capture"=>native::screen_capture(),"memory.store"=>call.arguments.get("content").and_then(|v|v.as_str()).ok_or("Missing memory content").and_then(|c|memory::memory_store("explicit".into(),c.into()).map(|m|m.id)),_=>Err(format!("Tool '{}' has no executor",call.name))};match result{Ok(output)=>ToolResult{success:true,tool:call.name.clone(),output:serde_json::json!({"data":output}),verified:true},Err(error)=>ToolResult{success:false,tool:call.name.clone(),output:serde_json::json!({"error":error}),verified:false}} }
fn prompt(ctx:&AgentContext,plan:&AgentPlan,registry:&ToolRegistry)->String{let tools=agent::tools_prompt(registry);let results=serde_json::to_string(plan).unwrap_or_default();format!("You are JARVIS. Return ONLY valid JSON matching one of these shapes: {{\"kind\":\"final\",\"response\":\"...\"}} or {{\"kind\":\"tool_call\",\"tool\":\"registered.name\",\"arguments\":{{}}}}. Use only registered tools. Never claim a tool succeeded without its verified result. Registered tools:\n{}\nUser request: {}\nPrevious execution context: {}",tools,ctx.user_request,results)}

#[tauri::command] pub async fn diagnostics()->BTreeMap<String,String>{let mut out=BTreeMap::new();let ollama=reqwest::get("http://localhost:11434/api/tags").await.is_ok();out.insert("Ollama".into(),if ollama{"Connected".into()}else{"Not connected".into()});out.insert("Text Model".into(),if ollama{"Configured locally".into()}else{"Not testable: Ollama unavailable".into()});out.insert("Terminal".into(),if Command::new("sh").arg("-c").arg("command -v sh").output().map(|x|x.status.success()).unwrap_or(false){"Ready".into()}else{"Unavailable".into()});out.insert("Memory".into(),if memory_path().exists(){"Stored locally".into()}else{"Ready".into()});out.insert("Microphone".into(),if cfg!(target_os="macos"){"Requires macOS permission".into()}else{"Not testable in this environment".into()});out.insert("TTS".into(),if cfg!(target_os="macos"){"macOS say available".into()}else{"Not testable in this environment".into()});out}

#[tauri::command] pub async fn agent_ask(text:String,state:State<'_,AppState>)->Result<AskResult,String>{let registry=agent::default_registry();let ctx=AgentContext{user_request:text.clone(),conversation:state.history.lock().await.clone(),..Default::default()};let mut plan=AgentPlan{steps:Vec::new(),final_response:None};let mut acts=vec![activity("Understanding request",None,"done")];for iteration in 0..10{acts.push(activity("Planning",Some(format!("Agent iteration {}",iteration+1)),"active"));let body=serde_json::json!({"model":"llama3.2","prompt":prompt(&ctx,&plan,&registry),"stream":false,"format":"json"});let response=reqwest::Client::new().post("http://localhost:11434/api/generate").json(&body).send().await.map_err(|_|"I can't connect to Ollama. Please start Ollama and try again.".to_string())?;if !response.status().is_success(){return Err("I can't connect to Ollama. Please start Ollama and try again.".into())}let data:OllamaResponse=response.json().await.map_err(|e|e.to_string())?;let decision:ModelDecision=serde_json::from_str(&data.response).map_err(|_|"Ollama returned invalid structured agent output.".to_string())?;match decision{ModelDecision::Final{response}=>{acts.push(activity("Final response",None,"done"));state.history.lock().await.push((text,response.clone()));return Ok(AskResult{reply:response,activities:acts})},ModelDecision::ToolCall{tool,arguments}=>{let call=ToolCall{name:tool,arguments};acts.push(activity("Calling registered tool",Some(call.name.clone()),"active"));let result=tool_result(&call,&registry);acts.push(activity("Tool completed",Some(if result.success{"Verified success".into()}else{result.output.to_string()}),if result.success{"done"}else{"error"}));plan.steps.push(call);plan.final_response=Some(serde_json::to_string(&result).unwrap_or_default());if !result.success && result.output.get("confirmation_required").is_some(){return Err(result.output.to_string())}}} }Err("JARVIS stopped after the maximum of 10 agent iterations without a final response.".into())}

#[tauri::command] pub async fn open_app(name:String)->Result<String,String>{open_app_inner(name)}
#[tauri::command] pub async fn remember(text:String)->Result<String,String>{memory::memory_store("explicit".into(),text).map(|m|m.id)}
#[tauri::command] pub fn classify_command(command:String)->String{risk(&command).into()}
#[tauri::command] pub fn run_safe_command(command:String,confirmed:bool)->Result<String,String>{run_command(command,confirmed)}
#[tauri::command] pub fn list_tools()->Vec<agent::ToolDefinition>{agent::default_registry().definitions()}
#[cfg_attr(mobile,tauri::mobile_entry_point)] pub fn run(){tauri::Builder::default().manage(AppState::default()).invoke_handler(tauri::generate_handler![diagnostics,agent_ask,open_app,remember,classify_command,run_safe_command,list_tools,memory::memory_store,memory::memory_search,memory::memory_get,memory::memory_delete,memory::memory_clear,settings::settings_get,settings::settings_update,settings::settings_reset,native::screen_capture,native::speak,native::stop_speaking]).run(tauri::generate_context!()).expect("error while running JARVIS");}
#[cfg(test)]mod tests{use super::*;#[test]fn risk_levels_are_ordered_by_protection(){assert_eq!(risk("pwd"),"LOW");assert_eq!(risk("git status"),"MEDIUM");assert_eq!(risk("rm ./cache"),"HIGH");assert_eq!(risk("rm -rf ./cache"),"CRITICAL");}}
